# Experiments

### Setup

In [ ]:
# You can set them inline
# import os
# os.environ["OPENAI_API_KEY"] = ""
# os.environ["LANGSMITH_API_KEY"] = ""
# os.environ["LANGSMITH_TRACING"] = "true"
# os.environ["LANGSMITH_PROJECT"] = "langsmith-notebook"

In [14]:
# Or you can use a .env file
from dotenv import load_dotenv
load_dotenv(dotenv_path="../../.env", override=True)

True

这是我们在整个课程中一直使用的 RAG 应用程序。

In [20]:
import os
import tempfile
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders.sitemap import SitemapLoader
from langchain_community.vectorstores import SKLearnVectorStore
from langchain_community.embeddings import DashScopeEmbeddings
from langsmith import traceable
from openai import OpenAI
from typing import List
import nest_asyncio

# TODO: Configure this model!
MODEL_NAME = "qwen3-max"
MODEL_PROVIDER = "qwen"
APP_VERSION = 1.0
RAG_SYSTEM_PROMPT = """You are an assistant for question-answering tasks. 
Use the following pieces of retrieved context to answer the latest question in the conversation. 
If you don't know the answer, just say that you don't know. 
Use three sentences maximum and keep the answer concise.
"""

openai_client = OpenAI(
    api_key=os.getenv("DASHSCOPE_API_KEY"),
    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1"
)

def get_vector_db_retriever():
    persist_path = os.path.join(tempfile.gettempdir(), "union.parquet")
    embd = DashScopeEmbeddings(model="text-embedding-v4")

    # If vector store exists, then load it
    if os.path.exists(persist_path):
        vectorstore = SKLearnVectorStore(
            embedding=embd,
            persist_path=persist_path,
            serializer="parquet"
        )
        return vectorstore.as_retriever(lambda_mult=0)

    # Otherwise, index LangSmith documents and create new vector store
    ls_docs_sitemap_loader = SitemapLoader(web_path="https://docs.smith.langchain.com/sitemap.xml", continue_on_failure=True)
    ls_docs = ls_docs_sitemap_loader.load()

    text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
        chunk_size=500, chunk_overlap=0
    )
    doc_splits = text_splitter.split_documents(ls_docs)

    vectorstore = SKLearnVectorStore.from_documents(
        documents=doc_splits,
        embedding=embd,
        persist_path=persist_path,
        serializer="parquet"
    )
    vectorstore.persist()
    return vectorstore.as_retriever(lambda_mult=0)

nest_asyncio.apply()
retriever = get_vector_db_retriever()

"""
retrieve_documents
- Returns documents fetched from a vectorstore based on the user's question
"""
@traceable(run_type="chain")
def retrieve_documents(question: str):
    return retriever.invoke(question)

"""
generate_response
- Calls `call_openai` to generate a model response after formatting inputs
"""
@traceable(run_type="chain")
def generate_response(question: str, documents):
    formatted_docs = "\n\n".join(doc.page_content for doc in documents)
    messages = [
        {
            "role": "system",
            "content": RAG_SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": f"Context: {formatted_docs} \n\n Question: {question}"
        }
    ]
    return call_openai(messages)

"""
call_openai
- Returns the chat completion output from OpenAI
"""
@traceable(
    run_type="llm",
    metadata={
        "ls_provider": MODEL_PROVIDER,
        "ls_model_name": MODEL_NAME
    }
)
def call_openai(messages: List[dict]) -> str:
    return openai_client.chat.completions.create(
        model=MODEL_NAME,
        messages=messages,
    )

"""
langsmith_rag
- Calls `retrieve_documents` to fetch documents
- Calls `generate_response` to generate a response based on the fetched documents
- Returns the model response
"""
@traceable(run_type="chain")
def langsmith_rag(question: str):
    documents = retrieve_documents(question)
    response = generate_response(question, documents)
    return response.choices[0].message.content

### Experiment

这里有几个重要组成部分:

1. 我们已经定义了一个评估器
2. 我们使用目标函数，将数据集示例（字典）传递给函数 `langsmith_rag` 所接受的输入类型（字符串）。

In [16]:
from langsmith import evaluate, Client

client = Client()
dataset_name = "RAG Application Golden Dataset"

def is_concise_enough(reference_outputs: dict, outputs: dict) -> dict:
    score = len(outputs["output"]) < 1.5 * len(reference_outputs["output"])
    return {"key": "is_concise", "score": int(score)}

def target_function(inputs: dict):
    return langsmith_rag(inputs["question"])

In [17]:
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="qwen3-max"
)

View the evaluation results for experiment: 'qwen3-max-0cb4af19' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=e09d451e-74cd-4724-9c8f-1ad0ab501815

12it [00:44,  3.71s/it]

### Modifying your Application

现在，让我们把模型换成 `qwen-plus`，看看它的性能如何！

进行此项更改，然后运行此代码片段！

In [21]:
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="qwen-plus"
)

View the evaluation results for experiment: 'qwen-plus-54cf6bef' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=3d3a122f-6f3e-4d41-934c-c9e05f2ea9b2

12it [00:35,  2.96s/it]

### 处理不同的数据片段

##### Dataset Version

可以使用 `list_examples` 函数中的 `as_of` 参数，在 SDK 中针对特定版本的数据集执行实验。

我们先尝试仅使用初始数据集运行实验。

In [22]:
evaluate(
    target_function,
    data=client.list_examples(dataset_name=dataset_name, as_of="initial dataset"),   # 使用 as_of 来指定版本
    evaluators=[is_concise_enough],
    experiment_prefix="initial dataset version"
)

View the evaluation results for experiment: 'initial dataset version-e07ef975' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=2c296cb7-e821-4138-aba9-609ed574a166

10it [00:29,  2.92s/it]

##### Dataset Split

你可以对数据集的特定拆分部分进行实验，我们来尝试对“关键示例”拆分部分进行实验。

In [23]:
evaluate(
    target_function,
    data=client.list_examples(dataset_name=dataset_name, splits=["Crucial Examples"]),  # 传入一个拆分列表
    evaluators=[is_concise_enough],
    experiment_prefix="Crucial Examples split"
)

View the evaluation results for experiment: 'Crucial Examples split-319a718c' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=5ab6dc7e-4a82-4dc1-91d6-90aa18ddcf93

6it [00:16,  2.71s/it]

##### Specific Data Points

你也可以指定要运行实验的单个数据点。

In [24]:
evaluate(
    target_function,
    data=client.list_examples(
        dataset_name=dataset_name, 
        example_ids=[   # 传入一个特定的 example_ids 列表
            # TODO: 你需要粘贴你自己的 example ids 才能使其正常工作！
            "e4d4a700-41e5-4dce-880c-c5fd17f26e75",
            "9f7c3004-23ab-4f45-9c97-4a28a8c6b53a"
        ]
    ),
    evaluators=[is_concise_enough],
    experiment_prefix="two specific example ids"
)

View the evaluation results for experiment: 'two specific example ids-39bd1314' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=43a91b73-2a33-4140-9967-0747418ce673

2it [00:06,  3.49s/it]

### Other Parameters

##### Repetitions

你可以多次进行实验，以确保获得一致的结果。

In [25]:
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="two repetitions",
    num_repetitions=2   # This field defaults to 1
)

View the evaluation results for experiment: 'two repetitions-b686367a' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=26dc2542-2240-4116-b7da-aca6295e2913

24it [01:09,  2.89s/it]

##### Concurrency

你还可以启动并发执行线程，使实验更快完成！

In [26]:
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="concurrency",
    max_concurrency=2,  # This defaults to None, so this is an improvement!
)

View the evaluation results for experiment: 'concurrency-5c66c91c' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=25750354-007d-4e6e-8c96-155dfaac3a49

12it [00:16,  1.40s/it]

##### Metadata 

你可以（也应该）为实验添加元数据，以便在用户界面中更容易找到它们。

In [27]:
evaluate(
    target_function,
    data=dataset_name,
    evaluators=[is_concise_enough],
    experiment_prefix="metadata added",
    metadata={  # 我们可以传递实验的自定义元数据，例如模型名称。
        "model_name": MODEL_NAME
    }
)

View the evaluation results for experiment: 'metadata added-33c895ee' at:
https://smith.langchain.com/o/e355c563-0e02-4eb4-baa7-8e9e5f87b8ff/datasets/81e7503c-2a58-44fc-9d54-7bd9090c34e5/compare?selectedSessions=c5357d6f-ec57-4eab-ab9c-d4c13bfae0cb

12it [00:29,  2.50s/it]